language: php

php:
  - 7.1
  - 7.0

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install

script:
 - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
 - sh -c 'wget https://scrutinizer-ci.com/ocular.phar;'
 - sh -c 'php ocular.phar code-coverage:upload --format=php-clover coverage.clover;'
